input-dir: experiment/input/

output-dir: experiment/output/

rml-dir: experiment/rml/

rml-file: darpa-engagement3lite2.rml

bg-knowledge: bg-knowledge/internal.ttl

provenance-rule: experiment/rule/provenance.rule

propagation-rule: experiment/rule/propagation.rule

alert-rule: experiment/rule/alert.rule


triple-store: graphdb

live-store: no

backup-file: no

confidential-dir:
 - /tmp/passwd
 - /var/log
 - /etc/shadow

recognized-host:
 - localhost
 - 127.0.0.1
 - 128.55.12.167
 - 10.0.4.1
 - 128.55.12.10
 - 193.40.5.73

field-filter:
 - EVENT_EXIT
 - EVENT_MPROTECT
 - EVENT_LOGIN
 #- EVENT_EXECUTE
 - EVENT_ACCEPT
 - EVENT_SENDMSG
 #- EVENT_SENDTO
 - EVENT_MODIFY_FILE_ATTRIBUTES
 - EVENT_RENAME
 #- EVENT_RECVFROM
 - EVENT_MODIFY_PROCESS
 - EVENT_CHANGE_PRINCIPAL
 - EVENT_LINK
 - EVENT_UNLINK
 - EVENT_CLOSE
 - EVENT_SIGNAL
 - EVENT_OPEN
 #- EVENT_READ
 #- EVENT_WRITE
 - EVENT_MMAP
 - EVENT_CREATE_OBJECT
 - EVENT_LSEEK
 - EVENT_FCNTL
 - EVENT_RECVMSG
 - EVENT_BIND
 - EVENT_OTHER
 - EVENT_CONNECT