input-dir: experiment/input/

output-dir: experiment/output/

rml-dir: experiment/rml/

rule-dir: experiment/rule/

rml-file: darpa-engagement3lite.rml

bg-knowledge: bg-knowledge/internal.ttl

triple-store: graphdb

live-store: yes

backup-file: no

confidential-dir:
 - /tmp/passwd
 - /var/log
 - /etc/shadow

recognized-host:
 - localhost
 - 127.0.0.1
 - 128.55.12.167
 #- 128.55.12.10

field-filter:
 - EVENT_EXIT
 #- EVENT_EXECUTE
 - EVENT_ACCEPT
 - EVENT_SENDMSG
 #- EVENT_SENDTO
 - EVENT_MODIFY_FILE_ATTRIBUTES
 - EVENT_RENAME
 #- EVENT_RECVFROM
 - EVENT_MODIFY_PROCESS
 - EVENT_CHANGE_PRINCIPAL
 - EVENT_LINK
 - EVENT_UNLINK
 - EVENT_CLOSE
 - EVENT_SIGNAL
 - EVENT_OPEN
 #- EVENT_READ
 #- EVENT_WRITE
 - EVENT_MMAP
 - EVENT_CREATE_OBJECT
 - EVENT_LSEEK
 - EVENT_FCNTL
 - EVENT_RECVMSG
 - EVENT_BIND
 - EVENT_OTHER
 - EVENT_CONNECT